<?php use app\Controllers\AppController; ?>

<section class="home h-100-content f-col center-x">
  <div class="row center-y">
    <div class="col home-header">
      <div class="row">
        <div class="col center-x"><?= AppController::svg('simpl') ?></div>
      </div>

      <div class="row">
        <div class="col center-x">
          <h1>Simpl</h1>
        </div>
      </div>

      <div class="row">
        <div class="col center-x">
          <p>This website is under construction! Please check back later.</p>
        </div>
      </div>
    </div>
  </div>
</section>
