<?php
use app\Controllers\AppController;
use app\Models\Url;
?>

<section class="home f-col g-row-4.5">
  <div class="row">
    <div class="col f-col g-row-1.5">
      <div class="row">
        <div class="col logo center-x">
          <?= AppController::svg('simpl') ?>
        </div>
      </div>

      <div class="row">
        <div class="col center-x">
          <h1>Simpl</h1>
        </div>
      </div>

      <div class="row">
        <div class="col center-x">
          <p>An easy-to-use PHP, HTML, Sass and TypeScript framework!</p>
        </div>
      </div>

      <div class="row center-x">
        <div class="col code-block f-row g-col-1 center-y f-0">
          <i class="fa fa-terminal"></i>
          <code><span class="command-name">npx</span> <span class="command-argument">@ijuantm/simpl-install</span></code>
          <span class="copy-code" title="Click to copy command to clipboard"><i class="fa fa-copy" aria-label="Copy to clipboard"></i></span>
        </div>
      </div>
    </div>
  </div>

  <div class="row center-x g-col-2 g-row-1.5">
    <a class="col card center-y" href="<?= Url::to('docs') ?>" aria-label="Link to the Simpl documentation">
      <div class="row g-col-2">
        <div class="col card-icon center f-0">
          <i class="fas fa-book" aria-hidden="true"></i>
        </div>

        <div class="col f-col g-row-1">
          <div class="row">
            <div class="col">
              <h2 class="card-title" data-typo="h4">Documentation</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p>Read the documentation for the Simpl framework.</p>
            </div>
          </div>
        </div>
      </div>
    </a>

    <a class="col card center-y" href="https://github.com/IJuanTM/simpl/" target="_blank" aria-label="Link to the Simpl GitHub repository">
      <div class="row g-col-2">
        <div class="col card-icon center f-0">
          <i class="fab fa-github" aria-hidden="true"></i>
        </div>
        <div class="col f-col g-row-1">
          <div class="row">
            <div class="col">
              <h2 class="card-title" data-typo="h4">GitHub</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p>View the source code on GitHub.</p>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</section>
