<?php ?>

<header class="w-100">
  <div class="row navbar">
    <nav class="col menu end-x">
      <div class="row nav-list w-auto f-0">
        <a class="col nav-item center f-0" href="<?= $this->url(REDIRECT) ?>" aria-label="Link to home page">Home</a>
        <a class="col nav-item center f-0" href="<?= $this->url('about') ?>" aria-label="Link to about page">About</a>
        <a class="col nav-item center f-0" href="<?= $this->url('docs') ?>" aria-label="Link to documentation page">Documentation</a>
        <a class="col nav-item center f-0" href="<?= $this->url('add-ons') ?>" aria-label="Link to add-ons page">Add-ons</a>
        <a class="col nav-item nav-button download center f-0" href="<?= $this->url('download') ?>" aria-label="Link to download page">Download</a>
      </div>
    </nav>

    <div class="col nav-options">
      <div class="row end-x h-100">
        <button class="col hamburger hamburger--squeeze f-0" type="button" aria-label="Expand navigation menu" aria-controls="navigation" aria-expanded="false" tabindex="1">
          <span class="hamburger-box center">
            <span class="hamburger-inner"></span>
          </span>
        </button>
      </div>
    </div>
  </div>
</header>
